---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hyprblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland-nvidia-open
image-version: latest # wayblue only supports the latest tag

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://download.docker.com/linux/fedora/docker-ce.repo
        - google-chrome.repo
      copr:
        - atim/starship
        - ublue-os/packages
    install:
      packages:
        - micro
        - starship
        # ostree development
        - ostree
        - rpm-ostree
        - flatpak-builder
        # containers
        - podman
        - buildah
        - skopeo
        - distrobox
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        # VMs
        - libvirt
        - virt-manager
        - qemu-kvm
        # apps
        - google-chrome-stable
        # development
        - nodejs
        - npm
        - gcc
        - gcc-c++
        - make
        - bison
        - flex
        - ncurses-devel
        - elfutils-libelf-devel
        - zlib-devel
        # CLI utilities
        - curl
        - fzf
        - git
        - ripgrep
        - zsh
        - stow
        - autojump-zsh
        - gnupg2
        - openssl
        - neomutt
        # homebrew
        - ublue-brew
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: bling
    install:
      - 1password # installs 1Password and CLI with proper GID configuration

  - type: script
    scripts:
      - install-neovim-nightly.sh
      - enable-brew-services.sh
      - enable-hyprblue-groups.sh

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
